export interface WordEntry {
  wordNe: string;
  wordEn: string;
  categoryNe: string;
  categoryEn: string;
  hintNe: string;
  hintEn: string;
}

export const WORD_LIST: WordEntry[] = [
  // ----------------- Food (खाना - 26 words) -----------------
  {
    wordNe: "मोमो",
    wordEn: "Momo",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "साथीसँग खाने",
    hintEn: "Popular with friends",
  },
  {
    wordNe: "दालभात",
    wordEn: "Dal Bhat",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "दैनिक खाना",
    hintEn: "Daily meal",
  },
  {
    wordNe: "चिया",
    wordEn: "Tea",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "गफ गर्ने बहाना",
    hintEn: "Excuse to chat",
  },
  {
    wordNe: "सेलरोटी",
    wordEn: "Sel Roti",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "चाडपर्वमा",
    hintEn: "Festival bread",
  },
  {
    wordNe: "चाउमिन",
    wordEn: "Chowmein",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "नूडल तर सुख्खा",
    hintEn: "Dry noodles",
  },
  {
    wordNe: "थुक्पा",
    wordEn: "Thukpa",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "झोल नूडल",
    hintEn: "Soup noodles",
  },
  {
    wordNe: "समोसा",
    wordEn: "Samosa",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "भित्र भराइ",
    hintEn: "Stuffed snack",
  },
  {
    wordNe: "पानीपुरी",
    wordEn: "Pani Puri",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "एकैचोटि खाने",
    hintEn: "Eat in one bite",
  },
  {
    wordNe: "अण्डा",
    wordEn: "Egg",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "ब्रेकफास्ट",
    hintEn: "Breakfast item",
  },
  {
    wordNe: "बिस्कुट",
    wordEn: "Biscuit",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "चियासँग",
    hintEn: "With tea",
  },
  {
    wordNe: "लस्सी",
    wordEn: "Lassi",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "चिसो पेय",
    hintEn: "Cold yogurt drink",
  },
  {
    wordNe: "दही",
    wordEn: "Curd",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "सेतो र नरम",
    hintEn: "White and soft",
  },
  {
    wordNe: "पिज्जा",
    wordEn: "Pizza",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "स्लाइसमा खाने",
    hintEn: "Eat in slices",
  },
  {
    wordNe: "बर्गर",
    wordEn: "Burger",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "हातले खाने",
    hintEn: "Eat with hands",
  },
  {
    wordNe: "चटपटे",
    wordEn: "Chatpate",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "पिरो र खट्टा",
    hintEn: "Spicy & tangy",
  },
  {
    wordNe: "गुन्द्रुक",
    wordEn: "Gundruk",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "सुकाएको साग",
    hintEn: "Fermented greens",
  },
  {
    wordNe: "ढिडो",
    wordEn: "Dhido",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "परम्परागत खाना",
    hintEn: "Traditional flour meal",
  },
  {
    wordNe: "रोटी",
    wordEn: "Roti",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "गोलाकार",
    hintEn: "Flat bread",
  },
  {
    wordNe: "आलु",
    wordEn: "Potato",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "तरकारीको राजा",
    hintEn: "King of vegetables",
  },
  {
    wordNe: "मासु",
    wordEn: "Meat",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "चाडपर्वमा",
    hintEn: "Festival favorite",
  },
  {
    wordNe: "दूध",
    wordEn: "Milk",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "सेतो पेय",
    hintEn: "White drink",
  },
  {
    wordNe: "माछा",
    wordEn: "Fish",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "पानीमा बस्ने",
    hintEn: "Lives in water",
  },
  {
    wordNe: "काउली",
    wordEn: "Cauliflower",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "फुल्ने तरकारी",
    hintEn: "Flowery vegetable",
  },
  {
    wordNe: "बन्दा",
    wordEn: "Cabbage",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "पातै पात",
    hintEn: "Leafy layers",
  },
  {
    wordNe: "आँप",
    wordEn: "Mango",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "फलफूलको राजा",
    hintEn: "King of fruits",
  },
  {
    wordNe: "स्याउ",
    wordEn: "Apple",
    categoryNe: "खाना",
    categoryEn: "Food",
    hintNe: "रातो फल",
    hintEn: "Red fruit",
  },

  // ----------------- Places (ठाउँ - 25 words) -----------------
  {
    wordNe: "काठमाडौं",
    wordEn: "Kathmandu",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "राजधानी",
    hintEn: "The Capital",
  },
  {
    wordNe: "पोखरा",
    wordEn: "Pokhara",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "फेवा ताल",
    hintEn: "Fewa Lake",
  },
  {
    wordNe: "स्कूल",
    wordEn: "School",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "पढ्ने ठाउँ",
    hintEn: "Place to study",
  },
  {
    wordNe: "अस्पताल",
    wordEn: "Hospital",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "बिरामी जाँच्ने",
    hintEn: "For the sick",
  },
  {
    wordNe: "बजार",
    wordEn: "Market",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "किनमेल",
    hintEn: "Shopping area",
  },
  {
    wordNe: "जिम",
    wordEn: "Gym",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "व्यायाम",
    hintEn: "Workout area",
  },
  {
    wordNe: "सिनेमा हल",
    wordEn: "Cinema Hall",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "फिल्म हेर्ने",
    hintEn: "Movie theater",
  },
  {
    wordNe: "मन्दिर",
    wordEn: "Temple",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "पूजा गर्ने",
    hintEn: "Worship place",
  },
  {
    wordNe: "घर",
    wordEn: "Home",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "बस्ने ठाउँ",
    hintEn: "Place to live",
  },
  {
    wordNe: "पार्क",
    wordEn: "Park",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "बच्चा खेल्ने",
    hintEn: "Playground/Relax",
  },
  {
    wordNe: "एयरपोर्ट",
    wordEn: "Airport",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "जहाज चढ्ने",
    hintEn: "Plane station",
  },
  {
    wordNe: "होटेल",
    wordEn: "Hotel",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "पाहुना बस्ने",
    hintEn: "Guest stay",
  },
  {
    wordNe: "पसल",
    wordEn: "Shop",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "सामान किन्ने",
    hintEn: "Buy goods",
  },
  {
    wordNe: "लाइब्रेरी",
    wordEn: "Library",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "किताब पढ्ने",
    hintEn: "Book room",
  },
  {
    wordNe: "जङ्गल",
    wordEn: "Jungle",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "रूखै रूख",
    hintEn: "Forest",
  },
  {
    wordNe: "पुल",
    wordEn: "Bridge",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "नदी तर्ने",
    hintEn: "Cross river",
  },
  {
    wordNe: "बैंक",
    wordEn: "Bank",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "पैसा राख्ने",
    hintEn: "Money place",
  },
  {
    wordNe: "हिमाल",
    wordEn: "Mountain",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "हिउँले ढाकिएको",
    hintEn: "Snowy peak",
  },
  {
    wordNe: "नदी",
    wordEn: "River",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "बगिरहने",
    hintEn: "Flowing water",
  },
  {
    wordNe: "गाउँ",
    wordEn: "Village",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "खेतबारी",
    hintEn: "Countryside",
  },
  {
    wordNe: "शहर",
    wordEn: "City",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "ठूला घर",
    hintEn: "Urban area",
  },
  {
    wordNe: "मैदान",
    wordEn: "Field",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "खेल्ने चउर",
    hintEn: "Open ground",
  },
  {
    wordNe: "बाटो",
    wordEn: "Road",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "हिँड्ने ठाउँ",
    hintEn: "Path for cars",
  },
  {
    wordNe: "गुफा",
    wordEn: "Cave",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "अँध्यारो सुरुङ",
    hintEn: "Dark tunnel",
  },
  {
    wordNe: "चिडियाखाना",
    wordEn: "Zoo",
    categoryNe: "ठाउँ",
    categoryEn: "Place",
    hintNe: "जनावर हेर्ने",
    hintEn: "Animal park",
  },

  // ----------------- Animals (जनावर - 25 words) -----------------
  {
    wordNe: "कुकुर",
    wordEn: "Dog",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "घर कुर्ने",
    hintEn: "Pet/Guard",
  },
  {
    wordNe: "बिरालो",
    wordEn: "Cat",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "मुसो समात्ने",
    hintEn: "Meow",
  },
  {
    wordNe: "गाई",
    wordEn: "Cow",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "राष्ट्रिय जनावर",
    hintEn: "National animal",
  },
  {
    wordNe: "बाघ",
    wordEn: "Tiger",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "डढेलो जस्तो",
    hintEn: "Striped predator",
  },
  {
    wordNe: "सिंह",
    wordEn: "Lion",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "जङ्गलको राजा",
    hintEn: "King of jungle",
  },
  {
    wordNe: "हात्ती",
    wordEn: "Elephant",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "लामो सुँढ",
    hintEn: "Long trunk",
  },
  {
    wordNe: "घोडा",
    wordEn: "Horse",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "छिटो दगुर्ने",
    hintEn: "Fast runner",
  },
  {
    wordNe: "बाख्रा",
    wordEn: "Goat",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "घाँस खाने",
    hintEn: "Grass eater",
  },
  {
    wordNe: "खरायो",
    wordEn: "Rabbit",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "लामो कान",
    hintEn: "Long ears",
  },
  {
    wordNe: "मृग",
    wordEn: "Deer",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "छिटो कुद्ने",
    hintEn: "Fast forest animal",
  },
  {
    wordNe: "बाँदर",
    wordEn: "Monkey",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "रूखमा उफ्रने",
    hintEn: "Tree jumper",
  },
  {
    wordNe: "भालु",
    wordEn: "Bear",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "मह मन पराउने",
    hintEn: "Honey lover",
  },
  {
    wordNe: "मुसो",
    wordEn: "Mouse",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "दुलामा बस्ने",
    hintEn: "Hole dweller",
  },
  {
    wordNe: "सर्प",
    wordEn: "Snake",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "खुट्टा नभएको",
    hintEn: "Legless",
  },
  {
    wordNe: "कछुवा",
    wordEn: "Turtle",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "बिस्तारै हिँड्ने",
    hintEn: "Slow walker",
  },
  {
    wordNe: "चरा",
    wordEn: "Bird",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "आकाशमा उड्ने",
    hintEn: "Flying creature",
  },
  {
    wordNe: "भैंसी",
    wordEn: "Buffalo",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "कालो र ठूलो",
    hintEn: "Black and bulky",
  },
  {
    wordNe: "भेडा",
    wordEn: "Sheep",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "ऊन दिने",
    hintEn: "Gives wool",
  },
  {
    wordNe: "गैंडा",
    wordEn: "Rhino",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "एउटा सिङ",
    hintEn: "One horn",
  },
  {
    wordNe: "चितुवा",
    wordEn: "Leopard",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "थोप्ला थोप्ला",
    hintEn: "Spotted cat",
  },
  {
    wordNe: "गधा",
    wordEn: "Donkey",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "भारी बोक्ने",
    hintEn: "Load carrier",
  },
  {
    wordNe: "ऊँट",
    wordEn: "Camel",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "मरुभूमिमा",
    hintEn: "Desert animal",
  },
  {
    wordNe: "स्याल",
    wordEn: "Jackal",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "चलाख",
    hintEn: "Clever/Cunning",
  },
  {
    wordNe: "लुम्बो",
    wordEn: "Fox",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "पुच्छर झुप्प",
    hintEn: "Bushy tail",
  },
  {
    wordNe: "खच्चर",
    wordEn: "Mule",
    categoryNe: "जनावर",
    categoryEn: "Animals",
    hintNe: "हिमालमा भारी",
    hintEn: "Mountain carrier",
  },

  // ----------------- Occupations (पेशा - 25 words) -----------------
  {
    wordNe: "डाक्टर",
    wordEn: "Doctor",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "बिरामी जाँच्ने",
    hintEn: "Treats patients",
  },
  {
    wordNe: "शिक्षक",
    wordEn: "Teacher",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "पढाउने",
    hintEn: "Teaches students",
  },
  {
    wordNe: "प्रहरी",
    wordEn: "Police",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "सुरक्षा दिने",
    hintEn: "Protects public",
  },
  {
    wordNe: "इन्जिनियर",
    wordEn: "Engineer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "नक्सा बनाउने",
    hintEn: "Designs buildings",
  },
  {
    wordNe: "पाइलट",
    wordEn: "Pilot",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "जहाज उडाउने",
    hintEn: "Flies airplanes",
  },
  {
    wordNe: "किसान",
    wordEn: "Farmer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "खेती गर्ने",
    hintEn: "Grows crops",
  },
  {
    wordNe: "ड्राइभर",
    wordEn: "Driver",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "गाडी चलाउने",
    hintEn: "Drives vehicles",
  },
  {
    wordNe: "गायक",
    wordEn: "Singer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "गीत गाउने",
    hintEn: "Sings songs",
  },
  {
    wordNe: "लेखक",
    wordEn: "Writer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "किताब लेख्ने",
    hintEn: "Writes books",
  },
  {
    wordNe: "नर्स",
    wordEn: "Nurse",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "सेवा गर्ने",
    hintEn: "Cares for sick",
  },
  {
    wordNe: "व्यापारी",
    wordEn: "Merchant",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "सामान बेच्ने",
    hintEn: "Sells goods",
  },
  {
    wordNe: "वकिल",
    wordEn: "Lawyer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "मुद्दा लड्ने",
    hintEn: "Defends in court",
  },
  {
    wordNe: "भान्छे",
    wordEn: "Cook/Chef",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "खाना पकाउने",
    hintEn: "Prepares food",
  },
  {
    wordNe: "सैनिक",
    wordEn: "Soldier",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "देशको रक्षा",
    hintEn: "Defends country",
  },
  {
    wordNe: "पत्रकार",
    wordEn: "Journalist",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "समाचार लेख्ने",
    hintEn: "Reports news",
  },
  {
    wordNe: "खेलाडी",
    wordEn: "Athlete",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "खेल खेल्ने",
    hintEn: "Plays sports",
  },
  {
    wordNe: "नाउ",
    wordEn: "Barber",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "कपाल काट्ने",
    hintEn: "Cuts hair",
  },
  {
    wordNe: "सिकर्मी",
    wordEn: "Carpenter",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "काठको काम",
    hintEn: "Wood worker",
  },
  {
    wordNe: "डकर्मी",
    wordEn: "Mason",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "घर बनाउने",
    hintEn: "Brick layer",
  },
  {
    wordNe: "धोबी",
    wordEn: "Laundryman",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "लुगा धुने",
    hintEn: "Washes clothes",
  },
  {
    wordNe: "माझी",
    wordEn: "Fisherman",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "माछा मार्ने",
    hintEn: "Catches fish",
  },
  {
    wordNe: "कलाकार",
    wordEn: "Artist",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "चित्र बनाउने",
    hintEn: "Paints pictures",
  },
  {
    wordNe: "मजदुर",
    wordEn: "Labourer",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "श्रम गर्ने",
    hintEn: "Hard worker",
  },
  {
    wordNe: "नेता",
    wordEn: "Politician",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "भाषण गर्ने",
    hintEn: "Gives speeches",
  },
  {
    wordNe: "ब्यापारी",
    wordEn: "Businessperson",
    categoryNe: "पेशा",
    categoryEn: "Occupations",
    hintNe: "अफिस जाने",
    hintEn: "Runs business",
  },

  // ----------------- Emotions (भावना - 25 words) -----------------
  {
    wordNe: "खुशी",
    wordEn: "Happy",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "हासो",
    hintEn: "Smiling face",
  },
  {
    wordNe: "दुखी",
    wordEn: "Sad",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "रुन्चे",
    hintEn: "Crying face",
  },
  {
    wordNe: "रिसाएको",
    wordEn: "Angry",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "झर्को लाग्ने",
    hintEn: "Mad/Furious",
  },
  {
    wordNe: "डर",
    wordEn: "Scared",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "काँप्ने",
    hintEn: "Afraid",
  },
  {
    wordNe: "माया",
    wordEn: "Love",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "मुटु",
    hintEn: "Heart symbol",
  },
  {
    wordNe: "थकान",
    wordEn: "Tired",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "सुत्न मन लाग्ने",
    hintEn: "Need sleep",
  },
  {
    wordNe: "भोक",
    wordEn: "Hungry",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "खाना चाहिने",
    hintEn: "Need food",
  },
  {
    wordNe: "तिर्खा",
    wordEn: "Thirsty",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "पानी चाहिने",
    hintEn: "Need water",
  },
  {
    wordNe: "अचम्म",
    wordEn: "Surprised",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "अनुहार रातो",
    hintEn: "Shocked",
  },
  {
    wordNe: "चिन्ता",
    wordEn: "Worried",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "सोचमग्न",
    hintEn: "Anxious",
  },
  {
    wordNe: "शान्त",
    wordEn: "Calm",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "नरिसाउने",
    hintEn: "Peaceful",
  },
  {
    wordNe: "गर्व",
    wordEn: "Proud",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "छाती फुल्ने",
    hintEn: "Feeling great",
  },
  {
    wordNe: "लाज",
    wordEn: "Shy",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "मुख छोप्ने",
    hintEn: "Blushing",
  },
  {
    wordNe: "ईर्ष्या",
    wordEn: "Jealous",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "डाहा गर्ने",
    hintEn: "Envious",
  },
  {
    wordNe: "घृणा",
    wordEn: "Hate",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "मन नपर्ने",
    hintEn: "Strong dislike",
  },
  {
    wordNe: "उत्साह",
    wordEn: "Excited",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "धैर्य नहुने",
    hintEn: "Very eager",
  },
  {
    wordNe: "अलमल",
    wordEn: "Confused",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "नबुझिने",
    hintEn: "Puzzled",
  },
  {
    wordNe: "एक्लो",
    wordEn: "Lonely",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "कोही नभएको",
    hintEn: "By self",
  },
  {
    wordNe: "दोषी",
    wordEn: "Guilty",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "गल्ती गरेको",
    hintEn: "Feeling bad",
  },
  {
    wordNe: "आशा",
    wordEn: "Hope",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "राम्रो होला",
    hintEn: "Wishful",
  },
  {
    wordNe: "दया",
    wordEn: "Kind",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "सहयोग गर्ने",
    hintEn: "Helpful nature",
  },
  {
    wordNe: "निद्रा",
    wordEn: "Sleepy",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "आँखा लोलाउने",
    hintEn: "Drowsy",
  },
  {
    wordNe: "बोर",
    wordEn: "Bored",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "जाँगर नभएको",
    hintEn: "Uninterested",
  },
  {
    wordNe: "पछुतो",
    wordEn: "Regret",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "हुनुपर्ने थियो",
    hintEn: "Remorse",
  },
  {
    wordNe: "विस्वास",
    wordEn: "Trust",
    categoryNe: "भावना",
    categoryEn: "Emotions",
    hintNe: "भरोसा",
    hintEn: "Confidence in someone",
  },

  // ----------------- Objects (वस्तु - 25 words) -----------------
  {
    wordNe: "कुर्सी",
    wordEn: "Chair",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "बस्ने",
    hintEn: "Sit on it",
  },
  {
    wordNe: "मोबाइल",
    wordEn: "Mobile",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "हातमा लिई हिड्ने",
    hintEn: "Carry in hand",
  },
  {
    wordNe: "किताब",
    wordEn: "Book",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "पढ्ने",
    hintEn: "Read it",
  },
  {
    wordNe: "कलम",
    wordEn: "Pen",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "लेख्ने",
    hintEn: "Write with it",
  },
  {
    wordNe: "घडी",
    wordEn: "Watch",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "समय देखाउने",
    hintEn: "Tells time",
  },
  {
    wordNe: "चश्मा",
    wordEn: "Glasses",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "आँखामा लगाउने",
    hintEn: "Wear on eyes",
  },
  {
    wordNe: "प्लेट",
    wordEn: "Plate",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "खाना राख्ने",
    hintEn: "Put food on",
  },
  {
    wordNe: "बस",
    wordEn: "Bus",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "सवारी",
    hintEn: "Public transport",
  },
  {
    wordNe: "कार",
    wordEn: "Car",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "चार पाङ्ग्रे",
    hintEn: "Four wheels",
  },
  {
    wordNe: "साइकल",
    wordEn: "Bicycle",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "पेडल मिलाउने",
    hintEn: "Pedal to move",
  },
  {
    wordNe: "टेलिभिजन",
    wordEn: "Television",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "कार्यक्रम हेर्ने",
    hintEn: "Watch shows",
  },
  {
    wordNe: "कम्प्युटर",
    wordEn: "Computer",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "टाइप गर्ने",
    hintEn: "Type on it",
  },
  {
    wordNe: "पङ्खा",
    wordEn: "Fan",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "हावा चलाउने",
    hintEn: "Moves air",
  },
  {
    wordNe: "ढक्नी",
    wordEn: "Cap/Hat",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "टाउकोमा लगाउने",
    hintEn: "Wear on head",
  },
  {
    wordNe: "अल्मारी",
    wordEn: "Wardrobe",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "कपडा राख्ने",
    hintEn: "Store clothes",
  },
  {
    wordNe: "तौलिया",
    wordEn: "Towel",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "पुछ्ने",
    hintEn: "Dry body",
  },
  {
    wordNe: "ओछ्यान",
    wordEn: "Bed",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "सुत्ने",
    hintEn: "Sleep on it",
  },
  {
    wordNe: "टेबुल",
    wordEn: "Table",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "सामान राख्ने",
    hintEn: "Put things on",
  },
  {
    wordNe: "बत्ती",
    wordEn: "Lamp",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "उज्यालो दिने",
    hintEn: "Gives light",
  },
  {
    wordNe: "रिंग",
    wordEn: "Ring",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "औंलामा लगाउने",
    hintEn: "Wear on finger",
  },
  {
    wordNe: "ब्याग",
    wordEn: "Bag",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "सामान राख्ने",
    hintEn: "Carry things",
  },
  {
    wordNe: "झोला",
    wordEn: "Jhola/Bag",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "काँधमा ओझेल्ने",
    hintEn: "Carry on shoulder",
  },
  {
    wordNe: "कागज",
    wordEn: "Paper",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "लेख्ने",
    hintEn: "Write on",
  },
  {
    wordNe: "काँच",
    wordEn: "Glass",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "पानी खाने",
    hintEn: "Drink from",
  },
  {
    wordNe: "ताला",
    wordEn: "Lock",
    categoryNe: "वस्तु",
    categoryEn: "Objects",
    hintNe: "घर बन्द गर्ने",
    hintEn: "Secure door",
  },

  // ----------------- Sports (खेलकुद - 25 words) -----------------
  {
    wordNe: "फुटबल",
    wordEn: "Football",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "खुट्टाले बल",
    hintEn: "Kick the ball",
  },
  {
    wordNe: "क्रिकेट",
    wordEn: "Cricket",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "ब्याट र बल",
    hintEn: "Bat and ball",
  },
  {
    wordNe: "वालिबल",
    wordEn: "Volleyball",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "जाल माथि बल",
    hintEn: "Ball over net",
  },
  {
    wordNe: "बास्केटबल",
    wordEn: "Basketball",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "घेरामा पार्ने",
    hintEn: "Ball in hoop",
  },
  {
    wordNe: "बादमिण्टन",
    wordEn: "Badminton",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "र्याकेट र शटल",
    hintEn: "Racket sport",
  },
  {
    wordNe: "तैराकी",
    wordEn: "Swimming",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "पानीमा",
    hintEn: "In water",
  },
  {
    wordNe: "दौड",
    wordEn: "Running",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "छिटो हिँड्ने",
    hintEn: "Fast on feet",
  },
  {
    wordNe: "कुस्ती",
    wordEn: "Wrestling",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "दुई जना लड्ने",
    hintEn: "Two people fight",
  },
  {
    wordNe: "टेनिस",
    wordEn: "Tennis",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "र्याकेटले बल",
    hintEn: "Racket and ball",
  },
  {
    wordNe: "गोल्फ",
    wordEn: "Golf",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "छोटो स्टिक",
    hintEn: "Club and ball",
  },
  {
    wordNe: "हकी",
    wordEn: "Hockey",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "लाठीले बल",
    hintEn: "Stick and ball",
  },
  {
    wordNe: "बक्सिङ",
    wordEn: "Boxing",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "मुक्काले लड्ने",
    hintEn: "Punch fight",
  },
  {
    wordNe: "योग",
    wordEn: "Yoga",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "शरीर तन्काउने",
    hintEn: "Stretch body",
  },
  {
    wordNe: "साइक्लिङ",
    wordEn: "Cycling",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "साइकल चलाउने",
    hintEn: "Ride bicycle",
  },
  {
    wordNe: "लामो दौड",
    wordEn: "Marathon",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "धेरै किलोमिटर",
    hintEn: "Long run",
  },
  {
    wordNe: "उचाइ कुद",
    wordEn: "High Jump",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "अग्लो उफ्रने",
    hintEn: "Jump high",
  },
  {
    wordNe: "लामो कुद",
    wordEn: "Long Jump",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "टाढा उफ्रने",
    hintEn: "Jump far",
  },
  {
    wordNe: "रग्बी",
    wordEn: "Rugby",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "हातले बल लाने",
    hintEn: "Carry ball",
  },
  {
    wordNe: "डन्डीबियो",
    wordEn: "Dandi Biyo",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "नेपाली खेल",
    hintEn: "Nepali traditional",
  },
  {
    wordNe: "लुगुरा पट्टी",
    wordEn: "Lugara Patti",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "गोलाकार खेल",
    hintEn: "Ring throw",
  },
  {
    wordNe: "रस्सी तान",
    wordEn: "Tug of War",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "रस्सी तान्ने",
    hintEn: "Pull rope",
  },
  {
    wordNe: "कबड्डी",
    wordEn: "Kabaddi",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "कबड्डी कबड्डी",
    hintEn: "Breath holding",
  },
  {
    wordNe: "चेस",
    wordEn: "Chess",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "बुद्धिको खेल",
    hintEn: "Board game",
  },
  {
    wordNe: "कारम",
    wordEn: "Carrom",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "गोली लाने",
    hintEn: "Strike pieces",
  },
  {
    wordNe: "पतङ्ग",
    wordEn: "Kite",
    categoryNe: "खेलकुद",
    categoryEn: "Sports",
    hintNe: "आकाशमा उडाउने",
    hintEn: "Fly in sky",
  },

  // ----------------- Entertainment (मनोरञ्जन - 25 words) -----------------
  {
    wordNe: "टिकटक",
    wordEn: "TikTok",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "छोटो भिडियो",
    hintEn: "Short videos",
  },
  {
    wordNe: "युट्युब",
    wordEn: "YouTube",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "भिडियो हेर्ने",
    hintEn: "Watch videos",
  },
  {
    wordNe: "फेसबुक",
    wordEn: "Facebook",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "सामाजिक सञ्जाल",
    hintEn: "Social media",
  },
  {
    wordNe: "नाच",
    wordEn: "Dance",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "सङ्गीतमा चाल",
    hintEn: "Move to music",
  },
  {
    wordNe: "गीत",
    wordEn: "Song",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "गाउने र सुन्ने",
    hintEn: "Sing and listen",
  },
  {
    wordNe: "चलचित्र",
    wordEn: "Movie",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "पर्दामा हेर्ने",
    hintEn: "Watch on screen",
  },
  {
    wordNe: "नाटक",
    wordEn: "Drama",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "मञ्चमा अभिनय",
    hintEn: "Stage acting",
  },
  {
    wordNe: "संगीत",
    wordEn: "Music",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "सुन्ने",
    hintEn: "Listen to",
  },
  {
    wordNe: "खेल",
    wordEn: "Game",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "मनोरञ्जन",
    hintEn: "For fun",
  },
  {
    wordNe: "कथा",
    wordEn: "Story",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "सुन्ने र पढ्ने",
    hintEn: "Listen or read",
  },
  {
    wordNe: "कार्टुन",
    wordEn: "Cartoon",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "बच्चा मन पराउने",
    hintEn: "Kids love",
  },
  {
    wordNe: "समाचार",
    wordEn: "News",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "दिनभरिको घटना",
    hintEn: "Daily events",
  },
  {
    wordNe: "रेडियो",
    wordEn: "Radio",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "सुन्ने मात्र",
    hintEn: "Listen only",
  },
  {
    wordNe: "सेल्फी",
    wordEn: "Selfie",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "आफ्नो फोटो",
    hintEn: "Own photo",
  },
  {
    wordNe: "भिडियो गेम",
    wordEn: "Video Game",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "कम्प्युटरमा खेल्ने",
    hintEn: "Play on screen",
  },
  {
    wordNe: "कविता",
    wordEn: "Poem",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "गाउने साहित्य",
    hintEn: "Lyrical verse",
  },
  {
    wordNe: "हाँसो",
    wordEn: "Comedy",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "हाँस्न लाउने",
    hintEn: "Makes laugh",
  },
  {
    wordNe: "डरलाग्दो",
    wordEn: "Horror",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "डर लाग्ने",
    hintEn: "Scary",
  },
  {
    wordNe: "प्रेम कथा",
    wordEn: "Romance",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "मायाको कथा",
    hintEn: "Love story",
  },
  {
    wordNe: "कमेडी शो",
    wordEn: "Comedy Show",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "ठट्टा मजाक",
    hintEn: "Jokes and fun",
  },
  {
    wordNe: "कन्सर्ट",
    wordEn: "Concert",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "जीवन्त सङ्गीत",
    hintEn: "Live music",
  },
  {
    wordNe: "पार्टी",
    wordEn: "Party",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "रमाइलो गर्ने",
    hintEn: "Have fun",
  },
  {
    wordNe: "पिकनिक",
    wordEn: "Picnic",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "बाहिर जाने",
    hintEn: "Outdoor trip",
  },
  {
    wordNe: "पुस्तक",
    wordEn: "Book",
    categoryNe: "मनोरञ्जन",
    categoryEn: "Entertainment",
    hintNe: "पढ्ने",
    hintEn: "Read",
  },
];
